### ISSUE TITLE
Integration into ddagent

### ISSUE THREAD

**Issue by ryanaverill** [mms-gianni/datadog-akamai-metrics#1]
Any idea how I integrate this into the datadog agent? I tried adding akamai.yaml into conf.d and akamai.py into checks but I'm still not getting data

**Comment by mms-gianni** [comment]
Did you ran it on foreground ? 

```
service datadog-agent stop
dd-agent configcheck
dd-agent foreground
```

It does not wirk with activated 2fa.

**Comment by ryanaverill** [comment]
foreground help me get that part working and I'm not using 2fa. One last question. 

Anything I have to enable in Akamai as I'm now getting "Failed to load json data"

I see you have: 

- site: "www.YOURCONFIG.ch"

Should this be set to the property name or hostname? I tried property name, hostname and Akamai ID and I can't get it to do anything except output "Failed to load json data"

Thanks!
